# python top_module.py --set tiling_inputs/AlexNet_no_tiling/settings_AlexNet_1_no_tiling.yaml --arch tiling_inputs/AlexNet_no_tiling/architecture_AlexNet_1_no_tiling.yaml --map tiling_inputs/AlexNet_no_tiling/mapping.yaml --mempool tiling_inputs/AlexNet_no_tiling/memory_pool_exploration.yaml
# python top_module.py --set tiling_inputs/AlexNet_no_tiling/settings_AlexNet_2_no_tiling.yaml --arch tiling_inputs/AlexNet_no_tiling/architecture_AlexNet_2_no_tiling.yaml --map tiling_inputs/AlexNet_no_tiling/mapping.yaml --mempool tiling_inputs/AlexNet_no_tiling/memory_pool_exploration.yaml
# python top_module.py --set tiling_inputs/AlexNet_no_tiling/settings_AlexNet_3_no_tiling.yaml --arch tiling_inputs/AlexNet_no_tiling/architecture_AlexNet_3_no_tiling.yaml --map tiling_inputs/AlexNet_no_tiling/mapping.yaml --mempool tiling_inputs/AlexNet_no_tiling/memory_pool_exploration.yaml
# python top_module.py --set tiling_inputs/AlexNet_no_tiling/settings_AlexNet_4_no_tiling.yaml --arch tiling_inputs/AlexNet_no_tiling/architecture_AlexNet_4_no_tiling.yaml --map tiling_inputs/AlexNet_no_tiling/mapping.yaml --mempool tiling_inputs/AlexNet_no_tiling/memory_pool_exploration.yaml
# python top_module.py --set tiling_inputs/AlexNet_no_tiling/settings_AlexNet_5_no_tiling.yaml --arch tiling_inputs/AlexNet_no_tiling/architecture_AlexNet_5_no_tiling.yaml --map tiling_inputs/AlexNet_no_tiling/mapping.yaml --mempool tiling_inputs/AlexNet_no_tiling/memory_pool_exploration.yaml

python top_module.py --set tiling_inputs/VGG16_no_tiling/settings_VGG16_1_no_tiling.yaml --arch tiling_inputs/VGG16_no_tiling/architecture_VGG16_1_no_tiling.yaml --map tiling_inputs/VGG16_no_tiling/mapping.yaml --mempool tiling_inputs/VGG16_no_tiling/memory_pool_exploration.yaml
python top_module.py --set tiling_inputs/VGG16_no_tiling/settings_VGG16_2_no_tiling.yaml --arch tiling_inputs/VGG16_no_tiling/architecture_VGG16_2_no_tiling.yaml --map tiling_inputs/VGG16_no_tiling/mapping.yaml --mempool tiling_inputs/VGG16_no_tiling/memory_pool_exploration.yaml
python top_module.py --set tiling_inputs/VGG16_no_tiling/settings_VGG16_3_no_tiling.yaml --arch tiling_inputs/VGG16_no_tiling/architecture_VGG16_3_no_tiling.yaml --map tiling_inputs/VGG16_no_tiling/mapping.yaml --mempool tiling_inputs/VGG16_no_tiling/memory_pool_exploration.yaml
python top_module.py --set tiling_inputs/VGG16_no_tiling/settings_VGG16_4_no_tiling.yaml --arch tiling_inputs/VGG16_no_tiling/architecture_VGG16_4_no_tiling.yaml --map tiling_inputs/VGG16_no_tiling/mapping.yaml --mempool tiling_inputs/VGG16_no_tiling/memory_pool_exploration.yaml
python top_module.py --set tiling_inputs/VGG16_no_tiling/settings_VGG16_5_no_tiling.yaml --arch tiling_inputs/VGG16_no_tiling/architecture_VGG16_5_no_tiling.yaml --map tiling_inputs/VGG16_no_tiling/mapping.yaml --mempool tiling_inputs/VGG16_no_tiling/memory_pool_exploration.yaml
python top_module.py --set tiling_inputs/VGG16_no_tiling/settings_VGG16_6_no_tiling.yaml --arch tiling_inputs/VGG16_no_tiling/architecture_VGG16_6_no_tiling.yaml --map tiling_inputs/VGG16_no_tiling/mapping.yaml --mempool tiling_inputs/VGG16_no_tiling/memory_pool_exploration.yaml
python top_module.py --set tiling_inputs/VGG16_no_tiling/settings_VGG16_7_no_tiling.yaml --arch tiling_inputs/VGG16_no_tiling/architecture_VGG16_7_no_tiling.yaml --map tiling_inputs/VGG16_no_tiling/mapping.yaml --mempool tiling_inputs/VGG16_no_tiling/memory_pool_exploration.yaml
python top_module.py --set tiling_inputs/VGG16_no_tiling/settings_VGG16_8_no_tiling.yaml --arch tiling_inputs/VGG16_no_tiling/architecture_VGG16_8_no_tiling.yaml --map tiling_inputs/VGG16_no_tiling/mapping.yaml --mempool tiling_inputs/VGG16_no_tiling/memory_pool_exploration.yaml
python top_module.py --set tiling_inputs/VGG16_no_tiling/settings_VGG16_9_no_tiling.yaml --arch tiling_inputs/VGG16_no_tiling/architecture_VGG16_9_no_tiling.yaml --map tiling_inputs/VGG16_no_tiling/mapping.yaml --mempool tiling_inputs/VGG16_no_tiling/memory_pool_exploration.yaml
python top_module.py --set tiling_inputs/VGG16_no_tiling/settings_VGG16_10_no_tiling.yaml --arch tiling_inputs/VGG16_no_tiling/architecture_VGG16_10_no_tiling.yaml --map tiling_inputs/VGG16_no_tiling/mapping.yaml --mempool tiling_inputs/VGG16_no_tiling/memory_pool_exploration.yaml
python top_module.py --set tiling_inputs/VGG16_no_tiling/settings_VGG16_11_no_tiling.yaml --arch tiling_inputs/VGG16_no_tiling/architecture_VGG16_11_no_tiling.yaml --map tiling_inputs/VGG16_no_tiling/mapping.yaml --mempool tiling_inputs/VGG16_no_tiling/memory_pool_exploration.yaml
python top_module.py --set tiling_inputs/VGG16_no_tiling/settings_VGG16_12_no_tiling.yaml --arch tiling_inputs/VGG16_no_tiling/architecture_VGG16_12_no_tiling.yaml --map tiling_inputs/VGG16_no_tiling/mapping.yaml --mempool tiling_inputs/VGG16_no_tiling/memory_pool_exploration.yaml
python top_module.py --set tiling_inputs/VGG16_no_tiling/settings_VGG16_13_no_tiling.yaml --arch tiling_inputs/VGG16_no_tiling/architecture_VGG16_13_no_tiling.yaml --map tiling_inputs/VGG16_no_tiling/mapping.yaml --mempool tiling_inputs/VGG16_no_tiling/memory_pool_exploration.yaml
