layer_info = {
    1: {'B': 1,
        'K': 96,
        'C': 3,
        'OY': 56,
        'OX': 56,
        'FY': 11,
        'FX': 11,
        'SY': 4,
        'SX': 4,
        'SFY': 1,
        'SFX': 1,
        'PY': 0,
        'PX': 0},
    2: {'B': 1,
        'K': 256,
        'C': 48,
        'OY': 26,
        'OX': 26,
        'FY': 5,
        'FX': 5,
        'SY': 1,
        'SX': 1,
        'SFY': 1,
        'SFX': 1,
        'PY': 0,
        'PX': 0},
    3: {'B': 1,
        'K': 384,
        'C': 256,
        'OY': 13,
        'OX': 13,
        'FY': 3,
        'FX': 3,
        'SY': 1,
        'SX': 1,
        'SFY': 1,
        'SFX': 1,
        'PY': 0,
        'PX': 0},
    4: {'B': 1,
        'K': 384,
        'C': 192,
        'OY': 13,
        'OX': 13,
        'FY': 3,
        'FX': 3,
        'SY': 1,
        'SX': 1,
        'SFY': 1,
        'SFX': 1,
        'PY': 0,
        'PX': 0},
    5: {'B': 1,
        'K': 256,
        'C': 192,
        'OY': 13,
        'OX': 13,
        'FY': 3,
        'FX': 3,
        'SY': 1,
        'SX': 1,
        'SFY': 1,
        'SFX': 1,
        'PY': 0,
        'PX': 0},
    # just an example of group convolution
    6: {'B': 1,
        'K': 256,  # Total for all groups
        'C': 192,  # Total for all groups
        'OY': 13,
        'OX': 13,
        'FY': 3,
        'FX': 3,
        'SY': 1,
        'SX': 1,
        'SFY': 1,
        'SFX': 1,
        'PY': 0,
        'PX': 0,
        'G' : 2}  # Number of groups
}
